# Generated by Django 3.0.6 on 2020-05-05 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocationDirectory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=5)),
                ('country_name', models.CharField(max_length=100)),
                ('city_name', models.CharField(max_length=100)),
                ('location_code', models.CharField(max_length=5)),
                ('post_code', models.CharField(max_length=5)),
                ('facilty_code', models.CharField(max_length=5)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('updation_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Location Directory',
                'db_table': 'location_directory',
            },
        ),
        migrations.AddIndex(
            model_name='locationdirectory',
            index=models.Index(fields=['country_name', 'city_name', 'post_code'], name='location_di_country_9b2a7c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='locationdirectory',
            unique_together={('country_name', 'city_name', 'post_code')},
        ),
    ]
